### ISSUE TITLE
HEMS rota/availability

### ISSUE THREAD

**Issue by RichardPilbery** [RichardPilbery/DAA_DES#2]
HT to confirm that HEMS rota is correct.

https://github.com/RichardPilbery/DAA_DES/blob/e0b65aef137c5a88f0e51fbcbb1d82bbde4233bd/utils.py#L17C3-L32C50

**Comment by htrebilcock** [comment]
Hi Richard, 

I've updated the HEMS rota 

 HEMS_ROTA = pd.DataFrame({
        "callsign"      : ["H70", "CC70", "H71", "CC71", "CC72"],
        "category"      : ["CC", "CC", "EC", "EC", "EC"],
        "type"          : ["helicopter", "car", "helicopter", "car", "car"],
        "summer_start1" : ["07:00", "07:00", "09:00", "09:00", "08:00"],
        "winter_start1" : ["07:00", "07:00", "07:00", "07:00", "08:00"],
        "summer_end1"   : ["17:00", "17:00", "19:00", "19:00", "18:00"],
        "winter_end1"   : ["17:00", "17:00", "17:00", "17:00", "18:00"],
        "summer_start2" : ["16:00", "16:00", "", "", ""],
        "winter_start2" : ["16:00", "16:00", "", "", ""],
        "summer_end2"   : ["02:00", "02:00", "", "", ""],
        "winter_end2"   : ["02:00", "02:00", "", "", ""],
        "service_freq"  : [12, 24, 12, 24, 24],                         # weeks
        "service_dur"   : [3, 1, 3, 1, 1]                               # weeks
    })
    HEMS_ROTA.set_index("callsign", inplace=True)

I still need to get the servicing data to confirm those bits but we can leave as is for now.

**Comment by RichardPilbery** [comment]
How is it that the same callsign can have over-lapping availability times? It doesn't really make sense to me.
