### ISSUE TITLE
Patient age distribution data needed

### ISSUE THREAD

**Issue by RichardPilbery** [RichardPilbery/DAA_DES#3]
Possibly stratified by AMPDS code and date/time

https://github.com/RichardPilbery/DAA_DES/blob/e0b65aef137c5a88f0e51fbcbb1d82bbde4233bd/class_patient.py#L14

**Comment by htrebilcock** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/H0264~1.TRE/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/H0264~1.TRE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<title>Untitled Spreadsheet</title>
<style>

</style>
</head>

<body link=blue vlink=purple>


AMPDS card | % of patients | Mean Age | Median age | Mode age | Age   distribution
-- | -- | -- | -- | -- | --
9 | 26% | 63 | 66 | 75 | Normal   negatively skewed
12 | 4% | 34 | 29 | 3 | log   normal?
17 | 10% | 51 | 54 | 65 | Normal
29 | 17% | 43 | 42 | 30 | Bimodal?



</body>

</html>


Card 29 age distribution:
![image](https://github.com/user-attachments/assets/f859af1a-7c56-498a-80db-998443a5d8d6)

Card 12 age distribution:
![image](https://github.com/user-attachments/assets/bd8b881c-ebbd-4c26-9732-f38610f6623e)

**Comment by RichardPilbery** [comment]
This is helpful. Could also provide data on card 7 (Burns) and then a category for all remaining codes? Table table above suggests we are capturing 57% of all calls at the moment.
