### ISSUE TITLE
Patient sex proportion data needed

### ISSUE THREAD

**Issue by RichardPilbery** [RichardPilbery/DAA_DES#4]
Possibly stratified by AMPDS code and date/time

https://github.com/RichardPilbery/DAA_DES/blob/e0b65aef137c5a88f0e51fbcbb1d82bbde4233bd/class_patient.py#L17

**Comment by htrebilcock** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/H0264~1.TRE/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/H0264~1.TRE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<title>Untitled Spreadsheet</title>
<style>

</style>
</head>

<body link=blue vlink=purple>


AMPDS card | % Male | %   Female
-- | -- | --
9 | 73% | 27%
12 | 49% | 51%
17 | 67% | 33%
29 | 72% | 28%



</body>

</html>

**Comment by RichardPilbery** [comment]
I've implemented this, but still just need proportions for card 7 (Burns)
